[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/thoas/go-funk"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/digineo/go-ping"
